### ISSUE TITLE
Driver fails some times  to translate ODBC functions into dialect of click-house server

### ISSUE THREAD

**Issue by XavierQuiniou** [ClickHouse/clickhouse-odbc#281] opened 2020-03-27 11:23 UTC
Test case
We encountered problems when using TABLEAU (BI software)
TABLEAU		        `2019.4`
This driver		`1.1.4`
CH server		`12.3.3.6`

Code tested with Visual Studio C++, just by compiling <tt>escape_sequences.cpp , lexer.cpp</tt> and related header files.

Examples that fail to be translated
<i>(full requests are listed at end of this issue description.)</i>

[space existing in colname already describe in issue #258]:
<code>SELECT \`my_base\`.\`PFX Ecosystem\` AS \`PFX_Ecosystem\`,…</code>

<code>{fn TIMESTAMPADD(SQL_TSI_HOUR,EXTRACT(HOUR FROM io_table_5`.`IO_Date`),CAST(`PFX_F_IO_TABLES_5`.`IO_Date` AS DATE))}</code>

<code>{fn FLOOR(EXTRACT(YEAR FROM `io_table`.`IO_Date`))}</code>

<code>{fn TRUNCATE(EXTRACT(DAY FROM `io_table_5`.`IO_Date`),0)}</code>

We have found that a few very simple code changes can resolve these issues.
<i>Original code is put in comment. Updated one is underlined in red.</i>	

![function_declare h](https://user-images.githubusercontent.com/58552786/77749770-e025e400-7022-11ea-9279-9eaef6c22528.png)
Update 1 : pragma put in comment.
Header is referenced twice by <tt>escape_sequences.cpp , lexer.cpp</tt>.
This pragma prohibits one of them from loading this header.
In our VS project, it was <tt>lexer.cpp</tt>.

Update 2 :Admit the presence of ‘space’ in a string \`…..\`

![lexer](https://user-images.githubusercontent.com/58552786/77749951-34c95f00-7023-11ea-9f62-d4274f126f52.png)
Update 3 : To manage ‘floor’
![escape_sequences](https://user-images.githubusercontent.com/58552786/77750084-7823cd80-7023-11ea-99c5-d7162f28af6b.png)

Test of ‘IDENT’ type is removed.
Since update 1, type of FLOOR token is no more IDENT, but FLOOR itself.

We hope you confirm the relevance of these remarks, and look forward to a new version of the driver.
(We have neither the skills nor the will to recompile it).
<hr>
Requests full text 

[floor] 

<code>SELECT `my_base`.`PFX Ecosystem` AS `PFX_Ecosystem`,
  `my_base`.`PFX_Group` AS `PFX_Group`,
  `my_base`.`PFX_Module` AS `PFX_Module`,
  `my_base`.`PFX_Site` AS `PFX_Site`,
  {fn FLOOR(EXTRACT(YEAR FROM `io_table`.`IO Date`))} AS `yr_IO_Date_ok`
FROM `io_table`
  LEFT JOIN `my_base` ON (`io_table`.`IO Nom Base` = `PFX_D_REFERENTIEL`.`PFX Nom Base`)
GROUP BY `my_base`.`PFX Ecosystem`,
  `my_base`.`PFX_Group`,
  `my_base`.`PFX_Module`,
  `my_base`.`PFX_Site`,
  `yr_IO_Date_ok`</code>

[truncate]

<code>SELECT `my_base_2`.`PFX_Ecosystem` AS `PFX_Ecosystem`,
  `my_base_2`.`PFX_Group` AS `PFX_Group`,
  `my_base_2`.`PFX_Module` AS `PFX_Module`,
  `my_base_2`.`PFX_Site` AS `PFX_Site`,
  CAST({fn TRUNCATE(EXTRACT(DAY FROM `io_table_5`.`IO_Date`),0)} AS INTEGER) AS `dy_IO_Date_ok`,
  CAST({fn TRUNCATE(EXTRACT(MONTH FROM `io_table_5`.`IO_Date`),0)} AS INTEGER) AS `mn_IO_Date_ok`,
  SUM(`io_table_5`.`IO_Nbr_Create`) AS `sum_IO_Nbr_Create_ok`
FROM `io_table_5`
  LEFT JOIN `my_base_2` ON (`io_table_5`.`IO_Nom_Base` = `PFX_D_REFERENTIEL_2`.`PFX_Nom_Base`)
WHERE (((CAST({fn TRUNCATE(EXTRACT(YEAR FROM `io_table_5`.`IO_Date`),0)} AS INTEGER) * 100) + CAST({fn TRUNCATE(EXTRACT(MONTH FROM `PFX_F_IO_TABLES_5`.`IO_Date`),0)} AS INTEGER)) IN (201910, 201911, 201912, 202001, 202002, 202003))
GROUP BY `my_base_2`.`PFX_Ecosystem`,
  `my_base_2`.`PFX_Group`,
  `my_base_2`.`PFX_Module`,
  `my_base_2`.`PFX_Site`,
 `dy_IO_Date_ok`,
  `mn_IO_Date_ok`</code>

[timestampadd]

<code>SELECT `my_base_2`.`PFX_Ecosystem` AS `PFX_Ecosystem`,
  `my_base_2`.`PFX_Group` AS `PFX_Group`,
  `my_base_2`.`PFX_Module` AS `PFX_Module`,
  `my_base_2`.`PFX_Site` AS `PFX_Site`,
  {fn TIMESTAMPADD(SQL_TSI_HOUR,EXTRACT(HOUR FROM `io_table_5`.`IO_Date`),CAST(`PFX_F_IO_TABLES_5`.`IO_Date` AS DATE))} AS `thr_IO_Date_ok`
FROM `io_table_5`
  LEFT JOIN `my_base_2` ON (`io_table_5`.`IO_Nom_Base` = `PFX_D_REFERENTIEL_2`.`PFX_Nom_Base`)
GROUP BY `my_base_2`.`PFX_Ecosystem`,
  `my_base_2`.`PFX_Group`,
  `my_base_2`.`PFX_Module`,
  `my_base_2`.`PFX_Site`,
  {fn TIMESTAMPADD(SQL_TSI_HOUR,EXTRACT(HOUR FROM `io_table_5`.`IO_Date`),CAST(`PFX_F_IO_TABLES_5`.`IO_Date` AS DATE))}</code>

**Comment by traceon** [comment] 2020-04-10 15:21
So, as I understand, there are 2 issues mentioned here:
1. improper handling of space in backtick-wrapped identifiers (issue #258 describes exactly that)
2. ODBC/SQL `{fn FLOOR(...)}`is not translated into ClickHouse's native `floor(...)`

Is my understanding correct?

**Comment by traceon** [comment] 2020-04-10 15:33
Well, the issue is only the space handling, looks like. So this issue can be considered duplicate of #258

**Comment by traceon** [comment] 2020-04-10 15:46
> (We have neither the skills nor the will to recompile it).

Regarding the building, you don't need any special skills, in addition to  what you've already demonstrated, to build the driver on your system. It may even be easier than the isolated source code tests that you did.

You can just follow the trivial instructions at [Building from sources](README.md#building-from-sources) and [Building from sources: Windows](README.md#building-from-sources-windows), and try the branch from PR #283 that should contain the fix for the issue.

**Comment by XavierQuiniou** [comment] 2020-04-10 15:49
Thank you for your mail.

We found an other pb when fn functions are nested :

Driver translates well in this case : { fn FA( ….., {fn FB(…)} …}
It fails if FB isn’t delimited by ‘{fn’, and ‘}’.
This case is issued from our Tableau experience. We added two small sections to your code.
Now, we seem to have found a solution.
in addition we have added a simplified log function, so we can detect  ‘invalid’ token.

I will send you modified cpp files  in the early evening.

Regards.





De : Denis Glazachev [mailto:notifications@github.com]
Envoyé : vendredi 10 avril 2020 17:34
À : ClickHouse/clickhouse-odbc
Cc : Xavier QUINIOU; Author
Objet : Re: [ClickHouse/clickhouse-odbc] Driver fails some times to translate ODBC functions into dialect of click-house server (#281)


Well, the issue is only the space handling, looks like. So this issue can be considered duplicate of #258<https://github.com/ClickHouse/clickhouse-odbc/issues/258>

**Comment by traceon** [comment] 2020-04-10 15:52
I would suggest to focus on the problem definition first, like a smallest possible example to reproduce the issue.

**Comment by XavierQuiniou** [comment] 2020-04-10 15:55
No problem.
Ok, I am now starting to collect the information you need.

De : Denis Glazachev [mailto:notifications@github.com]
Envoyé : vendredi 10 avril 2020 17:53
À : ClickHouse/clickhouse-odbc
Cc : Xavier QUINIOU; Author
Objet : Re: [ClickHouse/clickhouse-odbc] Driver fails some times to translate ODBC functions into dialect of click-house server (#281)


I would suggest to focus on the problem definition first, like a smallest possible example to reproduce the issue.

**Comment by XavierQuiniou** [comment] 2020-04-10 16:32
escape_sequences.cpp



Added code sections are identified by comment //DSIA



processFunction                              li 342



processIdentOrFunction             li 136



SELECTs to test :



--TIMESTAMPADD----------------------------------------------------------------

"SELECT `GDR_D_REFERENTIEL_2`.`GDR_Ecosystem` AS `GDR_Ecosystem`,\n"

"  `GDR_D_REFERENTIEL_2`.`GDR_Groupe` AS `GDR_Groupe`,\n"

"  `GDR_D_REFERENTIEL_2`.`GDR_Module` AS `GDR_Module`,\n"

"  `GDR_D_REFERENTIEL_2`.`GDR_Site` AS `GDR_Site`,\n"

"  {fn TIMESTAMPADD(SQL_TSI_HOUR,EXTRACT(HOUR FROM `GDR_F_IO_TABLES_5`.`IO_Date`),CAST(`GDR_F_IO_TABLES_5`.`IO_Date` AS DATE))} AS `thr_IO_Date_ok`\n"

"FROM `GDR_F_IO_TABLES_5`\n"

"  LEFT JOIN `GDR_D_REFERENTIEL_2` ON (`GDR_F_IO_TABLES_5`.`IO_Nom_Base`

= `GDR_D_REFERENTIEL_2`.`GDR_Nom_Base`)\n"

"GROUP BY `GDR_D_REFERENTIEL_2`.`GDR_Ecosystem`,\n"

"  `GDR_D_REFERENTIEL_2`.`GDR_Groupe`,\n"

"  `GDR_D_REFERENTIEL_2`.`GDR_Module`,\n"

"  `GDR_D_REFERENTIEL_2`.`GDR_Site`,\n"

"  {fn TIMESTAMPADD(SQL_TSI_HOUR,EXTRACT(HOUR FROM `GDR_F_IO_TABLES_5`.`IO_Date`), CAST(`GDR_F_IO_TABLES_5`.`IO_Date` AS DATE))}";



--TEST2------------------------------------------------------------------------

"SELECT {fn TIMESTAMPADD(SQL_TSI_HOUR,EXTRACT(HOUR FROM `odbc1`.`date`), CAST(`odbc1`.`date` AS DATE))} FROM `test`.`odbc1`";



--TEST2a------------------------------------------------------------------------

"SELECT {fn TIMESTAMPADD(SQL_TSI_HOUR, FLOOR(EXTRACT(YEAR FROM

`GDR_F_IO_TABLES`.`IO_Date`)) , CAST(`odbc1`.`date` AS DATE))} FROM `test`.`odbc1`";










/*

 https://docs.faircom.com/doc/sqlref/#33384.htm
 https://docs.microsoft.com/ru-ru/sql/odbc/reference/appendixes/time-date-and-interval-functions
 https://my.vertica.com/docs/7.2.x/HTML/index.htm#Authoring/SQLReferenceManual/Functions/Date-Time/TIMESTAMPADD.htm%3FTocPath%3DSQL%2520Reference%2520Manual%7CSQL%2520Functions%7CDate%252FTime%2520Functions%7C_____43

*/


#include "escape_sequences.h"
#include "lexer.h"

#include <map>
//#include <iostream> // DSIA for test

#include "SimpleLog.h"

using namespace std;

namespace {

    const std::map<const std::string, const std::string> fn_convert_map{
        {"SQL_TINYINT", "toUInt8"},
        {"SQL_SMALLINT", "toUInt16"},
        {"SQL_INTEGER", "toInt32"},
        {"SQL_BIGINT", "toInt64"},
        {"SQL_REAL", "toFloat32"},
        {"SQL_DOUBLE", "toFloat64"},
        {"SQL_VARCHAR", "toString"},
        {"SQL_DATE", "toDate"},
        {"SQL_TYPE_DATE", "toDate"},
        {"SQL_TIMESTAMP", "toDateTime"},
        {"SQL_TYPE_TIMESTAMP", "toDateTime"},
    };

#define DECLARE2(TOKEN, NAME) \
    { Token::TOKEN, NAME }

    /*traduction fonction ODBC -> fonction CH
    */
    const std::map<const Token::Type, const std::string> function_map{
    #include "function_declare.h"
    };

#undef DECLARE2

    const std::map<const Token::Type, const std::string> function_map_strip_params{
        {Token::CURRENT_TIMESTAMP, "now()"},
    };

    const std::map<const Token::Type, const std::string> literal_map{
        // {Token::SQL_TSI_FRAC_SECOND, ""},
        {Token::SQL_TSI_SECOND, "'second'"},
        {Token::SQL_TSI_MINUTE, "'minute'"},
        {Token::SQL_TSI_HOUR, "'hour'"},
        {Token::SQL_TSI_DAY, "'day'"},
        {Token::SQL_TSI_WEEK, "'week'"},
        {Token::SQL_TSI_MONTH, "'month'"},
        {Token::SQL_TSI_QUARTER, "'quarter'"},
        {Token::SQL_TSI_YEAR, "'year'"},
    };

    const std::map<const Token::Type, const std::string> timeadd_func_map{
        // {Token::SQL_TSI_FRAC_SECOND, ""},
        {Token::SQL_TSI_SECOND, "addSeconds"},
        {Token::SQL_TSI_MINUTE, "addMinutes"},
        {Token::SQL_TSI_HOUR, "addHours"},
        {Token::SQL_TSI_DAY, "addDays"},
        {Token::SQL_TSI_WEEK, "addWeeks"},
        {Token::SQL_TSI_MONTH, "addMonths"},
        {Token::SQL_TSI_QUARTER, "addQuarters"},
        {Token::SQL_TSI_YEAR, "addYears"},
    };


    string processEscapeSequencesImpl(const StringView seq, Lexer& lex);

    //DSIA : déclaration pour permettre la reciusivité
    // [processFunction --->]  processIdentOrFunction ---> processFunction
    string processFunction(const StringView seq, Lexer& lex); 

    string convertFunctionByType(const StringView& typeName) {
        const auto type_name_string = typeName.to_string();
        if (fn_convert_map.find(type_name_string) != fn_convert_map.end())
            return fn_convert_map.at(type_name_string);

        return string();
    }

    string processParentheses(const StringView seq, Lexer& lex) {
        string result;
        lex.SetEmitSpaces(true);
        result += lex.Consume().literal.to_string(); // (

        while (true) {
            const Token token(lex.Peek());

            // std::cerr << __FILE__ << ":" << __LINE__ << " : "<< token.literal.to_string() << " type=" << token.type << " go\n";

            if (token.type == Token::RPARENT) {
                result += token.literal.to_string();
                lex.Consume();
                break;
            }
            else if (token.type == Token::LPARENT) {
                result += processParentheses(seq, lex);
            }
            else if (token.type == Token::LCURLY) {
                lex.SetEmitSpaces(false);
                result += processEscapeSequencesImpl(seq, lex);
                lex.SetEmitSpaces(true);
            }
            else if (token.type == Token::EOS || token.type == Token::INVALID) {
                break;
            }
            else {
                result += token.literal.to_string();
                lex.Consume();
            }
        }

        return result;
    }

    /*
    *  DSIA on y a ajouté la détection d'une fonction ODBC (EXTRACT) qui n'est pas déclarée par { fn ... }
    */
    string processIdentOrFunction(const StringView seq, Lexer& lex) {

        logInner("processIdentOrFunction");
        while (lex.Match(Token::SPACE)) {
        }

        string result;
        const auto token = lex.Peek();
        //DSIA-----------------------------------------------------------------------
        if (token.type != Token::IDENT && lex.LookAhead(1).type == Token::LPARENT) {

            if (function_map.find(token.type) != function_map.end())
                result += function_map.at(token.type);
            else
                result += token.literal.to_string();
            lex.Consume();
            string r = processParentheses(seq, lex);
            result += r;
            return  result;
        }
        
        //---------------------------------------------------------------------------

        if (token.type == Token::LCURLY) {
            log("    Token::LCURLY found");
            lex.SetEmitSpaces(false);
            result += processEscapeSequencesImpl(seq, lex);
            lex.SetEmitSpaces(true);
        }

        else if (token.type == Token::LPARENT) {
            log("    Token::LPARENT found");
            result += processParentheses(seq, lex);
        }
        
        else if (token.type == Token::IDENT && lex.LookAhead(1).type == Token::LPARENT) { // CAST( ... )
            result += token.literal.to_string();   
            lex.Consume();
            string r = processParentheses(seq, lex);
            result += r;
        }

        else if (token.type == Token::NUMBER || token.type == Token::IDENT || token.type == Token::STRING) {
            if (token.type == Token::NUMBER )
            log("    Token::NUMBER || IDENT || STRING found : NUMBER");
            else if (token.type == Token::IDENT )
            log("    Token::NUMBER || IDENT || STRING found : IDENT");
            else if (token.type == Token::STRING)
            log("    Token::NUMBER || IDENT || STRING found : STRING");
            else
            log("    Token::NUMBER || IDENT || STRING found : ?????");
            log("    Token value :  " + token.literal.to_string() );
            result += token.literal.to_string();
            lex.Consume();
        }
        else if (function_map_strip_params.find(token.type) != function_map_strip_params.end()) {
            log("    function_map_strip_params.find(token.type) found : "+ function_map_strip_params.at(token.type));
            result += function_map_strip_params.at(token.type);
        }
        else {
            log("    ERR : return empty");
            log("          Token type :  " + token.type);
            log("          Token value :  " + token.literal.to_string());
            return "";
        }
        while (lex.Match(Token::SPACE)) {
        }
        logOuter("processIdentOrFunction : \n" + result);
        return result;
    }

    string processFunction(const StringView seq, Lexer& lex) { // traduction des fonctions ODBC
        logInner("processFunction");
        const Token fn(lex.Consume());
        if (fn.type == Token::CONVERT) {
            string result;
            if (!lex.Match(Token::LPARENT)) {
                logOuter("    processFunction :ERR - lex.Match(Token::LPARENT)");
                return seq.to_string();
            }

            auto num = processIdentOrFunction(seq, lex);
            if (num.empty()) {
                logOuter("processFunction :ERR - num.empty()");
                return seq.to_string();
            }
            result += num;

            while (lex.Match(Token::SPACE)) {
            }

            if (!lex.Match(Token::COMMA)) {
                return seq.to_string();
            }

            while (lex.Match(Token::SPACE)) {
            }

            Token type = lex.Consume();
            if (type.type != Token::IDENT) {
                return seq.to_string();
            }

            string func = convertFunctionByType(type.literal.to_string());

            if (!func.empty()) {
                while (lex.Match(Token::SPACE)) {
                }
                if (!lex.Match(Token::RPARENT)) {
                    return seq.to_string();
                }
                result = func + "(" + result + ")";
            }

            return result;

        }

        else if (fn.type == Token::TIMESTAMPADD) {
            string result;
            if (!lex.Match(Token::LPARENT))
                return seq.to_string();

            Token type = lex.Consume();
            if (timeadd_func_map.find(type.type) == timeadd_func_map.end())
                return seq.to_string();
            string func = timeadd_func_map.at(type.type);
            if (!lex.Match(Token::COMMA))
                return seq.to_string();

            auto ramount = processIdentOrFunction(seq, lex);
            if (ramount.empty())
                return seq.to_string();

            while (lex.Match(Token::SPACE)) {
            }

            if (!lex.Match(Token::COMMA)) {
                log("processFunction : ERR - missing COMMA");
                return seq.to_string();
            }


            auto rdate = processIdentOrFunction(seq, lex);
            if (rdate.empty())
                return seq.to_string();

            if (!func.empty()) {
                while (lex.Match(Token::SPACE)) {
                }
                if (!lex.Match(Token::RPARENT)) {
                    return seq.to_string();
                }
                result = func + "(" + rdate + ", " + ramount + ")";
            }
            return result;

        }
        else if (fn.type == Token::LOCATE) {
            string result;
            if (!lex.Match(Token::LPARENT))
                return seq.to_string();

            auto needle = processIdentOrFunction(seq, lex /*, false */);
            if (needle.empty())
                return seq.to_string();
            lex.Consume();

            auto haystack = processIdentOrFunction(seq, lex /*, false*/);
            if (haystack.empty())
                return seq.to_string();
            lex.Consume();

            auto offset = processIdentOrFunction(seq, lex /*, false */);
            lex.Consume();

            result = "position(" + haystack + "," + needle + ")";

            return result;

        }
        else if (fn.type == Token::LTRIM) {
            if (!lex.Match(Token::LPARENT))
                return seq.to_string();

            auto param = processIdentOrFunction(seq, lex /*, false*/);
            if (param.empty())
                return seq.to_string();
            lex.Consume();
            return "replaceRegexpOne(" + param + ", '^\\\\s+', '')";

        }
        else if (fn.type == Token::DAYOFWEEK) {
            if (!lex.Match(Token::LPARENT))
                return seq.to_string();

            auto param = processIdentOrFunction(seq, lex /*, false*/);
            if (param.empty())
                return seq.to_string();
            lex.Consume();
            return "if(toDayOfWeek(" + param + ") = 7, 1, toDayOfWeek(" + param + ") + 1)";
            /*
                } else if (fn.type == Token::DAYOFYEAR) { // Supported by ClickHouse since 18.13.0
                    if (!lex.Match(Token::LPARENT))
                        return seq.to_string();

                    auto param = processIdentOrFunction(seq, lex);
                    if (param.empty())
                        return seq.to_string();
                    lex.Consume();
                    return "( toRelativeDayNum(" + param + ") - toRelativeDayNum(toStartOfYear(" + param + ")) + 1 )";
            */
        }
        
        //DSIA-----------------------------------------------------------------------
        else if (fn.type != Token::IDENT && lex.Peek().type == Token::LPARENT) {
            //Peek(= = LokkAHead(0). C'est la parenthèse car le token a été consommé.
            string result;

            if (function_map.find(fn.type) != function_map.end())
                result += function_map.at(fn.type);
            else
                result += fn.literal.to_string();
            //lex.Consume();
            string r = processParentheses(seq, lex);
            result += r;
            return  result;
        }
        //----------------------------------------------------------------------------
       
        else if (function_map.find(fn.type) != function_map.end()) {
            string result = function_map.at(fn.type);

            auto func = result;
            lex.SetEmitSpaces(true);
            while (true) {
                const Token tok(lex.Peek());

                if (tok.type == Token::RCURLY) {
                    break;
                }
                else if (tok.type == Token::LCURLY) {
                    lex.SetEmitSpaces(false);
                    result += processEscapeSequencesImpl(seq, lex);
                    lex.SetEmitSpaces(true);
                }
                else if (tok.type == Token::EOS || tok.type == Token::INVALID) {
                    break;
                }
                else if (tok.type == Token::EXTRACT) {
                    result += processFunction(seq, lex);
                    //result += processIdentOrFunction(seq, lex);

                }
                else {
                    if (func != "EXTRACT" && literal_map.find(tok.type) != literal_map.end()) {
                        result += literal_map.at(tok.type);
                    }
                    else {
                        result += tok.literal.to_string();
                    }
                    lex.Consume();
                }
            }
            lex.SetEmitSpaces(false);
            logOuter("processFunction : " + result);
            return result;

        }
        else if (function_map_strip_params.find(fn.type) != function_map_strip_params.end()) {
            string result = function_map_strip_params.at(fn.type);

            if (lex.Peek().type == Token::LPARENT) {
                processParentheses(seq, lex); // ignore anything inside ( )
            }

            return result;
        }

        return seq.to_string();
    }

    string processDate(const StringView seq, Lexer& lex) {
        Token data = lex.Consume(Token::STRING);
        if (data.isInvalid()) {
            return seq.to_string();
        }
        else {
            return string("toDate(") + data.literal.to_string() + ")";
        }
    }

    string removeMilliseconds(const StringView token) {
        if (token.empty()) {
            return string();
        }

        const char* begin = token.data();
        const char* p = begin + token.size() - 1;
        const char* dot = nullptr;
        const bool quoted = (*p == '\'');
        if (quoted) {
            --p;
        }
        for (; p > begin; --p) {
            if (isdigit(*p)) {
                continue;
            }
            if (*p == '.') {
                if (dot) {
                    return token.to_string();
                }
                dot = p;
            }
            else {
                if (dot) {
                    return string(begin, dot) + (quoted ? "'" : "");
                }
                return token.to_string();
            }
        }

        return token.to_string();
    }

    string processDateTime(const StringView seq, Lexer& lex) {
        Token data = lex.Consume(Token::STRING);
        if (data.isInvalid()) {
            return seq.to_string();
        }
        else {
            return string("toDateTime(") + removeMilliseconds(data.literal) + ")";
        }
    }
    /**
    * seq est encadré par {,  } ces deux tokens sont consommés par CETTE fonction.
    *
    */
    string processEscapeSequencesImpl(const StringView seq, Lexer& lex) {
        string result;
        logInner("processEscapeSequencesImpl");
        if (!lex.Match(Token::LCURLY)) {
            log("    ERR - !lex.Match(Token::LCURLY)");
            return seq.to_string(); 
        }

        while (true) {
            while (lex.Match(Token::SPACE)) {
            }
            const Token tok(lex.Consume());

            switch (tok.type) {
            case Token::FN:
                result += processFunction(seq, lex);
                break;

            case Token::D:
                result += processDate(seq, lex);
                break;
            case Token::TS:
                result += processDateTime(seq, lex);
                break;

                // End of escape sequence
            case Token::RCURLY:
                logOuter("processEscapeSequencesImpl :");
                logOuter("    "+ result);
                return result;

                // Unimplemented
            case Token::T:
            default:
                logOuter("processEscapeSequencesImpl");
                log("    ERR : Le type de token n'est pas dans cette liste FN, D, TS, RCURLY ");
                log("          Token inattedu : " + tok.literal.to_string());
                return seq.to_string();
            }
        };
    }

    string processEscapeSequences(const StringView seq) {
        logInner("processEscapeSequences : ");
        log(seq.to_string());

        Lexer lex(seq);
        string r = processEscapeSequencesImpl(seq, lex);
        logOuter("processEscapeSequences :");
        logOuter("    "  +r);
        return r;
    }

} // namespace

/**
* traitement un bloc de  fonctions ODBC : { { } ... {} ...}
*
*/
std::string replaceEscapeSequences(const std::string& query) {

    
    logInner("replaceEscapeSequences");
    log(query);

    const char* p = query.c_str();
    const char* end = p + query.size();
    const char* st = p;
    int level = 0;
    std::string ret;

    while (p != end) {
        switch (*p) {
        case '{':
            if (level == 0) {
                if (st < p) {
                    ret += std::string(st, p);
                }
                st = p;
            }
            level++;
            break;

        case '}':
            if (level == 0) {
                // TODO unexpected '}'
            log("replaceEscapeSequences : ERR level = 0 - return \n" + query);
                return query;
            }
            if (--level == 0) {
                ret += processEscapeSequences(StringView(st, p + 1));
                st = p + 1;
            }
            break;
        }

        ++p;
    }

    if (st < p) {
        ret += std::string(st, p);
    }
    logOuter("replaceEscapeSequences");
    log(ret);
    loghr();
    closeLog();

    return  ret;
}

**Comment by traceon** [comment] 2020-04-10 16:46
@XavierQuiniou please state what other problem are you seeing. I am not able to effectively review such big changes, especially when it is not clear to me what problem they expose or fix.

Right now I see only these:
1. spaces in backticked identifiers (should be fixed in #283 )
2. nested escape sequences not supported?
3. anything else?

**Comment by XavierQuiniou** [comment] 2020-04-10 16:55
I have no other problem.


  1.  nested escape sequences not supported?
Nested escape seq. are supported when all seq. are put between {fn <seq>}
(as demonstrated in escape_sequence_ut.cpp)
In other case, nested seq. are ignored.
Perhaps, you need more simple request to test ?


De : Denis Glazachev [mailto:notifications@github.com]
Envoyé : vendredi 10 avril 2020 18:47
À : ClickHouse/clickhouse-odbc
Cc : Xavier QUINIOU; Mention
Objet : Re: [ClickHouse/clickhouse-odbc] Driver fails some times to translate ODBC functions into dialect of click-house server (#281)


@XavierQuiniou<https://github.com/XavierQuiniou> please state what other problem are you seeing. I am not able to effectively review such big changes, especially when it is not clear to me what problem they expose or fix.

Right now I see only these:

  1.  spaces in backticked identifiers (should be fixed in #283<https://github.com/ClickHouse/clickhouse-odbc/pull/283> )
  2.  nested escape sequences not supported?
  3.  anything else?

**Comment by traceon** [comment] 2020-04-10 16:59
Great, so a proper nested escape sequence support is what is left to add/ensure.

**Comment by XavierQuiniou** [comment] 2020-04-10 17:03
Yes definitely (for this issue).


De : Denis Glazachev [mailto:notifications@github.com]
Envoyé : vendredi 10 avril 2020 18:59
À : ClickHouse/clickhouse-odbc
Cc : Xavier QUINIOU; Mention
Objet : Re: [ClickHouse/clickhouse-odbc] Driver fails some times to translate ODBC functions into dialect of click-house server (#281)


Great, so a proper nested escape sequence support is what is left to add/ensure.

**Comment by traceon** [comment] 2020-04-10 23:12
> Driver translates well in this case : { fn FA( ….., {fn FB(…)} …}
> It fails if FB isn’t delimited by ‘{fn’, and ‘}’.

@XavierQuiniou take a look at this article: https://docs.microsoft.com/en-us/sql/odbc/reference/develop-app/scalar-function-calls

According to the examples from there, the current behavior of the driver is correct.

I.e, this:
```
... {fn orig_FA(orig_FB())} ...
```
should be translated to this:
```
... clickhouse_FA(orig_FB()) ...
```
and **not** to this:
```
... clickhouse_FA(clickhouse_FB()) ...
```
So, in order to achieve the latter, by standard, you have to specify:
```
... {fn orig_FA({fn orig_FB()})} ...
```

Does it make sense?

**Comment by traceon** [comment] 2020-04-11 01:14
Also, in some cases you might be hitting the issue which will be fixed by this PR #284

**Comment by XavierQuiniou** [comment] 2020-04-11 08:01
In fact this PR #284 seems to treat exactly my problem since it
references my issue #281.



________________________________
De : Denis Glazachev <notifications@github.com>
Envoyé : samedi 11 avril 2020 03:14
À : ClickHouse/clickhouse-odbc
Cc : Xavier QUINIOU; Mention
Objet : Re: [ClickHouse/clickhouse-odbc] Driver fails some times to translate ODBC functions into dialect of click-house server (#281)


Also, in some cases you might be hitting the issue which will be fixed by this PR #284<https://github.com/ClickHouse/clickhouse-odbc/pull/284>

-

**Comment by XavierQuiniou** [comment] 2020-04-11 16:19
Hi,


I can’t answer exactly.

If driver is OK, why my test request ‘TIMESTAMPADD’ fails ?


You can test it easily by running escape_sequences.cpp.

In other words, can you demonstrate that request from TABLEAU is not compliant with MS document ?



De : Denis Glazachev [mailto:notifications@github.com]
Envoyé : samedi 11 avril 2020 01:13
À : ClickHouse/clickhouse-odbc
Cc : Xavier QUINIOU; Mention
Objet : Re: [ClickHouse/clickhouse-odbc] Driver fails some times to translate ODBC functions into dialect of click-house server (#281)


Driver translates well in this case : { fn FA( ….., {fn FB(…)} …}
It fails if FB isn’t delimited by ‘{fn’, and ‘}’.

@XavierQuiniou<https://github.com/XavierQuiniou> take a look at this article: https://docs.microsoft.com/en-us/sql/odbc/reference/develop-app/scalar-function-calls

According to the examples from there, the current behavior of the driver is correct.

I.e, this:

... {fn orig_FA(orig_FB())} ...



should be translated to this:

... clickhouse_FA(orig_FB()) ...



and not to this:

... clickhouse_FA(clickhouse_FB()) ...



So, in order to achieve the latter, by standard, you have to specify:

... {fn orig_FA({fn orig_FB()})} ...



Does it make sense?

**Comment by traceon** [comment] 2020-04-11 16:53
That's exactly a manifestation of the bug #284 fixes.

**Closed** 2020-04-14 12:44 UTC
