### ISSUE TITLE
Add support for Decimal

### ISSUE THREAD

**Issue by e11it** [ClickHouse/clickhouse-odbc#119] opened 2018-09-17 08:35 UTC
Привет!

В КХ появилась поддрежка Decimal, но в tableau не видно колонок с типом Decimal.
ODBC драйвер стоит последний (2018-09-03).

Предполагаю - из-за отсутствия поддержки Decimal со стороны ODBC драйвера. Добавите? =)

**Comment by proller** [comment] 2018-09-17 17:42
Похоже что там одна строка нужна - 
https://github.com/yandex/clickhouse-odbc/pull/120/files#diff-6ac21cf2ca190e17bff143159a9574c3R36

**Comment by e11it** [comment] 2018-09-17 21:10
Собрал билд, из консоли вроде все ок. Завтра проверю с tableau.
Смущало дописать самому, это как получить / описать точность и маштаб.

Спасибо!

**Comment by proller** [comment] 2018-09-18 14:14
Но надо еще немного -
SQLDescribeCol - параметр out_decimal_digits
SQLColAttribute - поддержать SQL_DESC_PRECISION SQL_DESC_SCALE
самое сложное как всегда - найти софт который это все использует чтобы проверить корректность

**Comment by millin** [comment] 2019-08-13 10:29
@proller Could you also add SQL_DECIMAL to fn_convert_map?

PowerBI wants to convert values to decimal for SUM aggregation.

ClickHouse server received such kind of query:
```
select
    ...
    sum({ fn convert(`id`, SQL_DECIMAL) }) as `C1`
from
    ...
```

**Comment by alex-zaitsev** [comment] 2019-08-13 10:42
@millin , I wonder if it conversion can be turned off in PowerBI? Say, the problem is fixed in the driver. But it is a performance penalty to do such a conversion in every query.

**Comment by millin** [comment] 2019-08-13 11:03
I really don't know why Power BI wants to convert column before sum it and I did not find any way to disable.

My column is UInt64, but Power BI auto defined it as `Decimal Number`.
I manually changed it definition to `Whole Number` and now it works fine. 
Generated SQL still has conversion, but now to `float`, not `decimal`:
```
sum(toFloat64(`C1`)) as `C1`
```

**Comment by proller** [comment] 2019-08-13 12:53
Clickhouse have 4 decimal types: Decimal Decimal32 Decimal64 Decimal128
and 3 conversion functions: toDecimal32 toDecimal64 toDecimal128 - all requires additional precision param
how exactly { fn convert(`id`, SQL_DECIMAL) } should work?

**Comment by millin** [comment] 2019-08-13 13:32
As I understand, it should depend on SQL_DESC_PRECISION and SQL_DESC_SCALE

**Comment by traceon** [comment] 2019-10-28 11:53
Some of functionality around Decimal/Numeric and descriptors was merged to `master`, so this may start working, if not doing so currently.

**Comment by filimonov** [comment] 2019-11-12 21:25
So Decimal is supported now. If you have any problems with that - please open new issue.

**Closed by filimonov** 2019-11-12 21:25 UTC
Labels: enhancement

**Comment by bz-wow** [comment] 2021-08-13 01:41
> I really don't know why Power BI wants to convert column before sum it and I did not find any way to disable.
> 
> My column is UInt64, but Power BI auto defined it as `Decimal Number`.
> I manually changed it definition to `Whole Number` and now it works fine.
> Generated SQL still has conversion, but now to `float`, not `decimal`:
> 
> ```
> sum(toFloat64(`C1`)) as `C1`
> ```

Power BI has 2 number types, the whole number and the decimal number. However the value scope of whole number is less than int64 type as well as uint64 type. For example the biggest int64 is 9223372036854775807, this value is not supported as whole number in power bi, and has to assgin the decimal type. This may be why power bi wants to convert int64 data to decimal.
